apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    targetRevision: '*.*.*'
