apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - resources/application.yaml
  - resources/project.yaml
  - resources/configmap.yml
patches:
  - path: application.yaml
    target:
      kind: Application
  - path: project.yaml
    target:
      kind: AppProject
