apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - resources/ns.yaml
  - resources/overlay-cm.yaml
  - resources/app-projects/infrastructure/infrastructure-app-project.yaml
  - resources/app-projects/infrastructure/infrastructure-application.yaml
  - resources/ingr.yaml
  - resources/cert.yaml
  - resources/app-projects/media-server/media-server-app-project.yaml
  - resources/app-projects/media-server/media-server-application.yaml
  - resources/app-projects/projects/projects-app-project.yaml
  - resources/app-projects/projects/projects-application.yaml
patches:
  - path: patches/app-project.yaml
    target:
      kind: AppProject
  - path: patches/application.yaml
    target:
      kind: Application
#  - path: patches/dex-server-deployment.yaml
#    target:
#      kind: Deployment
#      name: argocd-dex-server
