apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-cloudflare
spec:
  acme:
    email: albert.vaillon21@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
