apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      services:
        - name: n8n
          port: http
      middlewares:
        - name: traefik-error-pages
          namespace: traefik
  tls:
    secretName: n8n-tls
