apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      services:
        - name: prometheus-prometheus
          port: http-web
      middlewares:
        - name: traefik-error-pages
          namespace: traefik
        - name: ak-outpost-authentik-embedded-outpost
          namespace: authentik
    - kind: Rule
      services:
        - name: prometheus-grafana
          port: http-web
      middlewares:
        - name: traefik-error-pages
          namespace: traefik
    - kind: Rule
      services:
        - name: prometheus-alertmanager
          port: http-web
      middlewares:
        - name: traefik-error-pages
          namespace: traefik
        - name: ak-outpost-authentik-embedded-outpost
          namespace: authentik
    - kind: Rule
      services:
        - name: ak-outpost-authentik-embedded-outpost
          namespace: authentik
          port: http
  tls:
    secretName: prometheus-tls
