apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
spec:
  source:
    repoURL: https://github.com/Eviive/nas-argocd-infrastructure
  destination:
    server: https://kubernetes.default.svc
