apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: traefik
resources:
  - resources/ns.yaml
  - resources/dashboard-cert.yaml
  - resources/error-pages-deploy.yaml
  - resources/error-pages-svc.yaml
  - resources/error-pages-middleware.yaml
  - resources/catch-all-ingr.yaml
  - resources/catch-all-cert.yaml
  - resources/catch-all-middleware.yaml
  - resources/logs-pvc.yaml
patches:
  - path: patches/dashboard-ingr.yaml
    target:
      kind: IngressRoute
      name: traefik-dashboard
configMapGenerator:
  - name: traefik-error-pages-html
    options:
      disableNameSuffixHash: true
    files:
      - assets/error-pages/404.html
      - 502.html=assets/error-pages/502-504.html
      - 503.html=assets/error-pages/502-504.html
      - 504.html=assets/error-pages/502-504.html
  - name: traefik-error-pages-conf
    options:
      disableNameSuffixHash: true
    files:
      - assets/error-pages/default.conf
