apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - resources/ns.yaml
  - resources/dashboard-cert.yaml
  - resources/error-pages-deployment.yaml
  - resources/error-pages-svc.yaml
  - resources/error-pages-middleware.yaml
configMapGenerator:
  - name: traefik-error-pages
    options:
      disableNameSuffixHash: true
    files:
      - assets/error-pages/404.html
      - assets/error-pages/500.html
      - assets/error-pages/501-599.html
