apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - resources/ns.yaml
  - resources/dashboard-cert.yaml
  - resources/error-pages-deployment.yaml
  - resources/error-pages-svc.yaml
  - resources/error-pages-middleware.yaml
  - resources/catch-all-ingr.yaml
  - resources/catch-all-cert.yaml
  - resources/catch-all-middleware.yaml
configMapGenerator:
  - name: traefik-error-pages
    options:
      disableNameSuffixHash: true
    files:
      - assets/error-pages/404.html
      - 502.html=assets/error-pages/502-504.html
      - 503.html=assets/error-pages/502-504.html
      - 504.html=assets/error-pages/502-504.html
