ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  web-ext:
    port: 8001
    expose:
      default: false
      ext: true
    exposedPort: 80
    protocol: TCP

service:
  additionalServices:
    ext: {}

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - websecure
    middlewares:
      - name: traefik-error-pages
      - name: ak-outpost-authentik-embedded-outpost
        namespace: authentik
    tls:
      secretName: traefik-dashboard-tls

providers:
  kubernetesCRD:
    allowCrossNamespace: true
