apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: projects
spec:
  description: Project for projects applications
  sourceRepos:
    - "*"
  destinations:
    - namespace: argocd
    - namespace: projects
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
