apiVersion: v2
name: jellyfin
type: application
version: 1.0.0
# renovate: image=jellyfin/jellyfin
appVersion: 10.11.9
dependencies:
  - name: base
    version: 1.0.0
    repository: file://../../../base
