apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  source:
    path: vault/$OVERLAY
  destination:
    namespace: vault
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
