apiVersion: v2
name: immich
type: application
version: 1.0.0
dependencies:
  - name: base
    version: 1.0.0
    repository: file://../../../base
  - name: immich
    version: 0.13.1
    repository: oci://ghcr.io/immich-app/immich-charts
  - name: cluster
    version: 0.8.1
    repository: https://cloudnative-pg.github.io/charts
