base:
  pvcs:
    - name: library
      accessModes:
        - ReadWriteOnce
      size: 200Gi
      storageClassName: nfs-hdd-2
      folder: immich/library
  ingressRoutes:
    - routes:
        - match: Host(`immich.home.albertv.dev`)
          services:
            - name: immich-server
              port: http
      dnsNames:
        - immich.home.albertv.dev

immich:
  controllers:
    main:
      containers:
        main:
          env:
            DB_HOSTNAME: immich-cluster-rw.immich.svc.cluster.local
            DB_DATABASE_NAME: immich
            DB_USERNAME:
              valueFrom:
                secretKeyRef:
                  name: immich
                  key: db-username
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich
                  key: db-password
            REDIS_HOSTNAME: redis-master.redis.svc.cluster.local
            REDIS_DBINDEX: 3
            REDIS_USERNAME:
              valueFrom:
                secretKeyRef:
                  name: immich
                  key: redis-username
            REDIS_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich
                  key: redis-password
  immich:
    persistence:
      library:
        existingClaim: immich-library
  machine-learning:
    persistence:
      cache:
        type: persistentVolumeClaim
        size: 10Gi
        accessMode: ReadWriteOnce
        storageClass: nfs-ssd-1

cluster:
  version:
    postgresql: "18"
  databases:
    - name: immich
      owner: immich
      extensions:
        - name: vchord
  cluster:
    instances: 1
    imageCatalogRef:
      kind: ImageCatalog
      name: immich-cluster
    postgresql:
      shared_preload_libraries:
        - vchord.so
    initdb:
      database: immich
      secret:
        name: immich-cnpg
    storage:
      storageClass: nfs-ssd-1
    annotations:
      folder: immich-cnpg
