apiVersion: v2
name: nextcloud
type: application
version: 1.0.0
dependencies:
  - name: base
    version: 1.0.0
    repository: file://../../../base
  - name: nextcloud
    version: 9.2.2
    repository: https://nextcloud.github.io/helm
  - name: cluster
    version: 0.7.0
    repository: https://cloudnative-pg.github.io/charts
