base:
  ingressRoutes:
    - routes:
        - match: Host(`nextcloud.home.albertv.dev`)
          services:
            - name: nextcloud
              port: http
      dnsNames:
        - nextcloud.home.albertv.dev

nextcloud:
  nextcloud:
    host: nextcloud.home.albertv.dev
    extraEnv:
      - name: OVERWRITEHOST
        value: nextcloud.home.albertv.dev
      - name: OVERWRITEPROTOCOL
        value: https
      - name: OVERWRITECLIURL
        value: https://nextcloud.home.albertv.dev
  internalDatabase:
    enabled: false
  externalDatabase:
    enabled: true
    type: postgresql
    host: nextcloud-cluster-rw.nextcloud.svc.cluster.local
    existingSecret:
      enabled: true
      secretName: nextcloud
  persistence:
    enabled: true
    storageClass: nfs-ssd-1
    annotations:
      folder: nextcloud/main
    nextcloudData:
      enabled: true
      storageClass: nfs-hdd-1
      annotations:
        folder: nextcloud/data
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

cluster:
  version:
    postgresql: "16.11-minimal-trixie"

  databases:
    - name: nextcloud
      owner: nextcloud

  cluster:
    instances: 1
    initdb:
      database: nextcloud
      secret:
        name: nextcloud-cnpg
    storage:
      storageClass: nfs-ssd-1
    annotations:
      folder: nextcloud-cnpg
