apiVersion: v2
name: projects
type: application
version: 1.0.0
dependencies:
  - name: base
    version: 1.0.0
    repository: file://../../../base
  - name: cluster
    version: 0.8.1
    repository: https://cloudnative-pg.github.io/charts
