apiVersion: v2
name: cert-manager
type: application
version: 1.0.0
dependencies:
  - name: base
    version: 1.0.0
    repository: file://../../../base
  - name: cert-manager
    version: 1.20.2
    repository: https://charts.jetstack.io
