image:
  tag: v3.3

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.home.albertv.dev`)
    entryPoints: ["https-internal"]
    middlewares:
      - name: traefik-dashboard-auth

extraObjects:
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: traefik-dashboard-auth
    spec:
      basicAuth:
        secret: traefik-dashboard-auth-secret
