image:
  tag: v3.3

service:
  spec:
    loadBalancerIP: 192.168.1.201
  additionalServices:
    ext:
      spec:
        loadBalancerIP: 192.168.1.202

ingressRoute:
  dashboard:
    matchRule: Host(`traefik.home.albertv.dev`)
    middlewares:
      - name: traefik-dashboard-oidc
        namespace: traefik

experimental:
  plugins:
    oidc:
      moduleName: github.com/sevensolutions/traefik-oidc-auth
      version: v0.5.0
