apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media-server
  labels:
    {{- include "base.labels" (dict "context" $ "component" "media-server") | nindent 4 }}
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/Eviive/nas-argocd-infrastructure
        revision: HEAD
        files:
          - path: charts/apps/media-server/*/config.json
  templatePatch: |
    {{ `{{- if eq (default "false" (get . "autoSync") | toString) "true" }}` }}
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    {{ `{{- end }}` }}
  template:
    metadata:
      name: "{{ `{{ .name }}` }}"
    spec:
      project: media-server
      source:
        repoURL: https://github.com/Eviive/nas-argocd-infrastructure
        path: "charts/apps/media-server/{{ `{{ .name }}` }}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ `{{ .name }}` }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - "ServerSideApply={{ `{{ default \"false\" (get . \"serverSideApply\") }}` }}"
