apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: application.yaml
    target:
      kind: Application
  - path: configmap.yaml
    target:
      kind: ConfigMap
      name: infrastructure-apps-config
replacements:
  - path: infrastructure-apps-config-replacement.yaml
