apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: application.yaml
    target:
      kind: Application
  - path: overlay-cm.yaml
    target:
      kind: ConfigMap
      name: infrastructure-apps-overlay
replacements:
  - path: application-overlay-replacement.yaml
