apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 70.3.0
    releaseName: prometheus
    namespace: prometheus
    includeCRDs: true
    valuesFile: ../../base/values.yaml
