apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 77.1.0
    releaseName: prometheus
    namespace: prometheus
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-production.yaml
patches:
  - path: patches/ingr.yaml
    target:
      kind: IngressRoute
      name: prometheus
  - path: patches/cert.yaml
    target:
      kind: Certificate
      name: prometheus
