base:
  deployments:
    - name: error-pages
      containers:
        - name: nginx
          image:
            repository: nginx
            tag: 1.31.1@sha256:608a100c71651bf5b773c89083b4a1ad7ef4b2bd05d7a7e552271e03123692ad
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 2
            periodSeconds: 2
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: conf
          configMap:
            name: traefik-error-pages-conf
        - name: html
          configMap:
            name: traefik-error-pages-html

  services:
    - name: error-pages
      ports:
        - name: http
          port: 80
          targetPort: http

  ingressRoutes:
    - name: dashboard
      routes:
        - match: Host(`traefik.home.albertv.dev`)
          services:
            - kind: TraefikService
              name: api@internal
          enableAuthentikMiddleware: true
      authentikProxyProviderRouteMatch: Host(`traefik.home.albertv.dev`)
      dnsNames:
        - traefik.home.albertv.dev
    - name: catch-all
      routes:
        - match: HostRegexp(`^.+$`)
          priority: 1
          services:
            - name: traefik-error-pages
              port: http
          middlewares:
            - name: traefik-catch-all
          disableErrorPagesMiddleware: true
      dnsNames:
        - "*.home.albertv.dev"
    - name: catch-all-ext
      external: true
      routes:
        - match: HostRegexp(`^.+$`)
          priority: 1
          services:
            - name: traefik-error-pages
              port: http
          middlewares:
            - name: traefik-catch-all
          disableErrorPagesMiddleware: true

  middlewares:
    - name: catch-all
      spec:
        replacePath:
          path: /404.html
    - name: error-pages
      spec:
        errors:
          status:
            - 502-504
          service:
            name: traefik-error-pages
            port: http
          query: /{status}.html

  configMaps:
    - name: error-pages-html
      files:
        404.html: assets/error-pages/404.html
        502.html: assets/error-pages/502-504.html
        503.html: assets/error-pages/502-504.html
        504.html: assets/error-pages/502-504.html
    - name: error-pages-conf
      files:
        default.conf: assets/error-pages/default.conf

traefik:
  ports:
    web:
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true

    web-ext:
      port: 8001
      expose:
        default: false
        ext: true
      exposedPort: 80
      protocol: TCP
      forwardedHeaders:
        trustedIPs:
          - "127.0.0.1/32"
          - "10.244.0.0/16"

  service:
    annotations:
      metallb.io/loadBalancerIPs: 192.168.1.201
    additionalServices:
      ext:
        type: ClusterIP

  providers:
    kubernetesCRD:
      allowCrossNamespace: true
