apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-ui
  namespace: vault
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      services:
        - name: vault-ui
          port: 8200
  tls:
    secretName: vault-ha-tls
