nfs-subdir-external-provisioner:
  nfs:
    server: truenas.home.albertv.dev
    path: /mnt/hdd-2/k8s-nfs
  storageClass:
    name: nfs-hdd-2
    reclaimPolicy: Retain
    pathPattern: ${.PVC.annotations.folder}
