- op: replace
  path: /spec/routes/0/match
  value: Host(`prometheus.home.albertv.dev`)
- op: replace
  path: /spec/routes/1/match
  value: Host(`grafana.home.albertv.dev`)
- op: replace
  path: /spec/routes/2/match
  value: Host(`alertmanager.home.albertv.dev`)
