apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: "https://argocd.home.albertv.dev"
  dex.config: |
    connectors:
    - config:
        issuer: https://authentik.home.albertv.dev/application/o/argocd/
        clientID: qglmwiWOqURfhAkgClYQNKeVBfXau6fU5UO8SMlB
        clientSecret: $dex.authentik.clientSecret
        insecureEnableGroups: true
        scopes:
          - openid
          - profile
          - email
      name: authentik
      type: oidc
      id: authentik
