base:
  deployments:
    - containers:
        - name: radarr
          image:
            repository: linuxserver/radarr
            tag: 6.3.0@sha256:2b2c1c05eb3f648d2c80dfab9486147dd7bb0ad4d77fa972fc1c5de8f1da3738
          env:
            - name: PUID
              value: "1057"
            - name: PGID
              value: "1056"
          ports:
            - name: http
              containerPort: 7878
          volumeMounts:
            - name: config
              mountPath: /config
            - name: movies
              mountPath: /movies
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: movies
          persistentVolumeClaim:
            claimName: radarr-movies
        - name: downloads
          persistentVolumeClaim:
            claimName: radarr-downloads

  pvcs:
    - name: config
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      storageClassName: nfs-ssd-1
      folder: media-server/radarr/config
    - name: movies
      accessModes:
        - ReadWriteOnce
      size: 200Gi
      storageClassName: nfs-hdd-1
      folder: media-server/movies
    - name: downloads
      accessModes:
        - ReadWriteOnce
      size: 400Gi
      storageClassName: nfs-hdd-1
      folder: media-server/downloads

  services:
    - ports:
        - name: http
          port: 80
          targetPort: http

  ingressRoutes:
    - routes:
        - match: Host(`radarr.home.albertv.dev`)
          services:
            - name: radarr
              port: http
          enableAuthentikMiddleware: true
      authentikProxyProviderRouteMatch: Host(`radarr.home.albertv.dev`)
      dnsNames:
        - radarr.home.albertv.dev
