apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfs-client-provisioner-hdd-1
resources:
  - github.com/kubernetes-sigs/nfs-subdir-external-provisioner//deploy?ref=nfs-subdir-external-provisioner-4.0.18
  - resources/ns.yaml
nameSuffix: -hdd-1
patches:
  - path: patches/sc.yaml
    target:
      kind: StorageClass
      name: nfs-client
  - path: patches/deploy.yaml
    target:
      kind: Deployment
      name: nfs-client-provisioner
