{
 "title": "Kubernetes Events",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events Details",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"integrations/kubernetes/eventhandler\"} | namespace =~ `$namespace` |~ `(?i)$search` | label_format involved_object_separator=\": \""
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (type) (count_over_time({job=\"integrations/kubernetes/eventhandler\"} | logfmt | namespace=~`$namespace` |~ `(?i)$search` [$__interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"integrations/kubernetes/eventhandler\"} | namespace=~`$namespace` |~ `(?i)$search` | logfmt | type=\"Warning\" [$__interval]))",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Image Pull Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"integrations/kubernetes/eventhandler\"} | namespace =~ `$namespace` | reason = `Failed` |= `Error: ImagePullBackOff` |~ `(?i)$search` [$__interval]))"
    }
   ]
  },
  {
   "title": "Liveness Probe Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"integrations/kubernetes/eventhandler\"} | namespace=~`$namespace` | reason=\"Killing\" |= \"failed liveness probe\" |~ `(?i)$search` [$__interval]))"
    }
   ]
  },
  {
   "title": "Volume Mount Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"integrations/kubernetes/eventhandler\"} | namespace=~`$namespace` | reason=\"FailedMount\" |~ `(?i)$search` [$__interval]))"
    }
   ]
  },
  {
   "title": "Scheduling Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"integrations/kubernetes/eventhandler\"} | namespace=~`$namespace` | reason=\"FailedScheduling\" |~ `(?i)$search` [$__interval]))"
    }
   ]
  },
  {
   "title": "Container OOM Killed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"integrations/kubernetes/eventhandler\"} | namespace=~`$namespace` | reason=\"OOMKilling\" |~ `(?i)$search` [$__interval]))"
    }
   ]
  },
  {
   "title": "Container Crashed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"integrations/kubernetes/eventhandler\"} | namespace=~`$namespace` | reason=\"BackOff\" |~ `(?i)$search` [$__interval]))"
    }
   ]
  },
  {
   "title": "Pod Evicted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"integrations/kubernetes/eventhandler\"} | namespace=~`$namespace` | reason=\"TaintManagerEviction\" |= \"Marking for deletion Pod\" |~ `(?i)$search` [$__interval]))"
    }
   ]
  },
  {
   "title": "System OOM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"integrations/kubernetes/eventhandler\"} | namespace=~`$namespace` | reason=\"SystemOOM\" |~ `(?i)$search` [$__interval]))"
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events by Reason",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (reason) (count_over_time({job=\"integrations/kubernetes/eventhandler\"} | namespace=~`$namespace` |~ `(?i)$search` [$__interval]))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Events by Namespace",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (namespace) (count_over_time({job=\"integrations/kubernetes/eventhandler\"} | namespace=~`$namespace` |~ `(?i)$search` [$__interval]))",
       "legendFormat": "{{metadata_namespace}}"
      }
     ]
    },
    {
     "title": "Events by Source",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 6, "x": 12, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (sourcecomponent) (count_over_time({job=\"integrations/kubernetes/eventhandler\"} | namespace=~`$namespace` |~ `(?i)$search` | logfmt [$__interval]))",
       "legendFormat": "{{source_component}}"
      }
     ]
    },
    {
     "title": "Events by Kind",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 6, "x": 18, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (kind) (count_over_time({job=\"integrations/kubernetes/eventhandler\"} | namespace=~`$namespace` |~ `(?i)$search` | logfmt [$__interval]))",
       "legendFormat": "{{involvedObject_kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"integrations/kubernetes/eventhandler\"} |~ `(?i)$search` | namespace =~ `$namespace`"
      }
     ]
    }
   ]
  }
 ]
}