apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
spec:
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      initContainers:
        - name: gluetun
          image: qmcgaw/gluetun:v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
          restartPolicy: Always
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - (ip rule del table 51820; ip -6 rule del table 51820) || true
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: flaresolverr-gluetun-config
              mountPath: /gluetun
        - name: ping
          image: busybox@sha256:e3652a00a2fabd16ce889f0aa32c38eec347b997e73bd09e69c962ec7f8732ee
          command:
            - /bin/sh
            - -c
            - |
              while ! ping -c 1 cloudflare.com; do
                echo "Ping failed, retrying in 5 seconds..."
                sleep 5
              done
              echo "Ping successful, proceeding..."
      containers:
        - name: flaresolverr
          image: alexfozor/flaresolverr:pr-1300-experimental
          ports:
            - name: http
              containerPort: 8191
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 2
      volumes:
        - name: flaresolverr-gluetun-config
          persistentVolumeClaim:
            claimName: flaresolverr-gluetun-config
