apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: alexfozor/flaresolverr:pr-1300
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8191
