apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flaresolverr-gluetun-config
  annotations:
    folder: flaresolverr-gluetun/config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-ssd-1
