apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
  - resources/ip-address-pool.yaml
  - resources/l2-advertisement.yaml
transformers:
  - transformers/ns-transformer.yaml
