apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/metallb/metallb//config/native?ref=v0.15.2
  - resources/ip-address-pool.yaml
  - resources/l2-advertisement.yaml
transformers:
  - transformers/ns-transformer.yaml
