apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: metallb
resources:
  - github.com/metallb/metallb/config/native?ref=v0.14.9
  - resources/ip-address-pool.yaml
  - resources/l2-advertisement.yaml
