apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../base
helmCharts:
  - name: nfs-subdir-external-provisioner
    repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    version: 4.0.18
    releaseName: nfs-hdd-1-provisioner
    namespace: nfs-hdd-1-provisioner
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-production.yaml
