global:
  postgresql:
    auth:
      existingSecret: postgresql-password
      secretKeys:
        adminPasswordKey: "ADMIN_PASSWORD"
        replicationPasswordKey: "REPLICATION_PASSWORD"

primary:
  persistence:
    enabled: true
    volumeName: postgresql-primary
    storageClass: nfs-ssd-1
    annotations:
      folder: postgresql/primary
    size: 10Gi
