base:
  deployments:
    - containers:
        - name: scraparr
          image:
            repository: thegameprofi/scraparr
            tag: 3.2.0@sha256:b9f79a85c33564dfdb1e50ab3d725faeb27b89f4ad5cae7013e39e2f572a8085
          ports:
            - name: http-metrics
              containerPort: 7100
          volumeMounts:
            - name: config
              mountPath: /scraparr/config
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: scraparr-config

  services:
    - clusterIP: None
      ports:
        - name: http-metrics
          port: 7100
          targetPort: http-metrics

  serviceMonitors:
    - endpoints:
        - port: http-metrics
          path: /metrics

  configMaps:
    - name: grafana-dashboard
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Media Server
      files:
        scraparr.json: assets/grafana-dashboard.json
