base:
  deployments:
    - containers:
        - name: scraparr
          image:
            repository: thegameprofi/scraparr
            tag: 3.1.0@sha256:24e089fa6a0a98be365a653a256ccfed5ae85571229f83c41c3c92530dad60d9
          ports:
            - name: http-metrics
              containerPort: 7100
          volumeMounts:
            - name: config
              mountPath: /scraparr/config
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: scraparr-config

  services:
    - clusterIP: None
      ports:
        - name: http-metrics
          port: 7100
          targetPort: http-metrics

  serviceMonitors:
    - endpoints:
        - port: http-metrics
          path: /metrics

  configMaps:
    - name: grafana-dashboard
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Media Server
      files:
        scraparr.json: assets/grafana-dashboard.json
