apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.29.1
    releaseName: vault
    namespace: vault
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-production.yaml
