server:
  image:
    tag: "1.18.3"
  extraEnvironmentVars:
    VAULT_ADDR: http://127.0.0.1:8200
    VAULT_CACERT: /vault/userconfig/vault-ha-tls/vault.ca
    VAULT_TLSCERT: /vault/userconfig/vault-ha-tls/vault.crt
    VAULT_TLSKEY: /vault/userconfig/vault-ha-tls/vault.key
    VAULT_SEAL_TYPE: azurekeyvault
  extraSecretEnvironmentVars:
    - envName: AZURE_TENANT_ID
      secretName: vault-auto-unseal-azure-secret
      secretKey: tenant_id
    - envName: AZURE_CLIENT_ID
      secretName: vault-auto-unseal-azure-secret
      secretKey: client_id
    - envName: AZURE_CLIENT_SECRET
      secretName: vault-auto-unseal-azure-secret
      secretKey: client_secret
    - envName: VAULT_AZUREKEYVAULT_VAULT_NAME
      secretName: vault-auto-unseal-azure-secret
      secretKey: vault_name
    - envName: VAULT_AZUREKEYVAULT_KEY_NAME
      secretName: vault-auto-unseal-azure-secret
      secretKey: key_name
  volumes:
    - name: userconfig-vault-ha-tls
      secret:
        defaultMode: 420
        secretName: vault-ha-tls
  volumeMounts:
    - mountPath: /vault/userconfig/vault-ha-tls
      name: userconfig-vault-ha-tls
      readOnly: true
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      config: |
        cluster_name = "k8s-nas"
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            leader_ca_cert_file = "/vault/userconfig/vault-ha-tls/vault.ca"
            leader_client_cert_file = "/vault/userconfig/vault-ha-tls/vault.crt"
            leader_client_key_file = "/vault/userconfig/vault-ha-tls/vault.key"
          }
          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
            leader_ca_cert_file = "/vault/userconfig/vault-ha-tls/vault.ca"
            leader_client_cert_file = "/vault/userconfig/vault-ha-tls/vault.crt"
            leader_client_key_file = "/vault/userconfig/vault-ha-tls/vault.key"
          }
          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
            leader_ca_cert_file = "/vault/userconfig/vault-ha-tls/vault.ca"
            leader_client_cert_file = "/vault/userconfig/vault-ha-tls/vault.crt"
            leader_client_key_file = "/vault/userconfig/vault-ha-tls/vault.key"
          }
        }

        disable_mlock = true
        service_registration "kubernetes" {}

ui:
  enabled: true
