apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-auto-unseal-azure-role-binding
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
roleRef:
  kind: Role
  name: vault-auto-unseal-azure-role
  apiGroup: rbac.authorization.k8s.io
