apiVersion: v2
name: authentik
type: application
version: 1.0.0
dependencies:
  - name: base
    version: 1.0.0
    repository: file://../../../base
  - name: authentik
    version: 2026.5.5
    repository: https://charts.goauthentik.io
  - name: cluster
    version: 0.8.1
    repository: https://cloudnative-pg.github.io/charts
