apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-catch-all
spec:
  entryPoints:
    - websecure
    - websecure-ext
  routes:
    - kind: Rule
      match: HostRegexp(`^.+$`)
      priority: 1
      services:
        - name: traefik-error-pages
          port: http
      middlewares:
        - name: traefik-catch-all
  tls:
    secretName: traefik-catch-all-tls
