apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-error-pages
spec:
  selector:
    matchLabels:
      app: traefik-error-pages
  template:
    metadata:
      labels:
        app: traefik-error-pages
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.4
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: conf
          configMap:
            name: traefik-error-pages-conf
        - name: html
          configMap:
            name: traefik-error-pages-html
