apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-error-pages
spec:
  errors:
    status:
      - "502-504"
    service:
      name: traefik-error-pages
      port: http
    query: "/{status}.html"
