apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-error-pages
spec:
  selector:
    matchLabels:
      app: traefik-error-pages
  template:
    metadata:
      labels:
        app: traefik-error-pages
    spec:
      containers:
        - name: nginx
          image: nginx:1.31.1@sha256:5aca99593157f4ae539a5dec1092a0ad8762f8e2eb1789085a13a0f5622369f6
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 2
            periodSeconds: 2
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: conf
          configMap:
            name: traefik-error-pages-conf
        - name: html
          configMap:
            name: traefik-error-pages-html
