apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-error-pages
spec:
  selector:
    matchLabels:
      app: traefik-error-pages
  template:
    metadata:
      labels:
        app: traefik-error-pages
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: traefik-error-pages
              mountPath: /usr/share/nginx/html
      volumes:
        - name: traefik-error-pages
          configMap:
            name: traefik-error-pages
