apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-logs
  annotations:
    folder: logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: traefik-nfs
