apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: traefik-nfs
parameters:
  pathPattern: "${.PVC.namespace}/${.PVC.annotations.folder}"
provisioner: nfs-ssd-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
