apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.16.3
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-production.yaml
patches:
  - path: issuer.yaml
    target:
      kind: Issuer
  - path: cloudflare-issuer.yaml
    target:
      kind: Issuer
      name: cloudflare
