apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-cloudflare
spec:
  acme:
    privateKeySecretRef:
      name: cert-manager-cloudflare-issuer-private-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-cloudflare-api-token
              key: api-token
