server:
  volumeMounts:
    - name: assets
      mountPath: /web/dist/assets/images/custom
      subPath: images
      readOnly: true
  volumes:
    - name: assets
      persistentVolumeClaim:
        claimName: authentik-assets
  envFrom:
    - secretRef:
        name: authentik-env

worker:
  envFrom:
    - secretRef:
        name: authentik-env

redis:
  enabled: false
