server:
  volumeMounts:
    - name: assets
      mountPath: /web/dist/assets/images/custom
      subPath: images
      readOnly: true
  volumes:
    - name: assets
      persistentVolumeClaim:
        claimName: authentik-assets
  envFrom:
    - secretRef:
        name: authentik-env

worker:
  envFrom:
    - secretRef:
        name: authentik-env

postgresql:
  enabled: true
  global:
    storageClass: authentik-nfs
    postgresql:
      auth:
        existingSecret: authentik-env
        secretKeys:
          adminPasswordKey: AUTHENTIK_POSTGRESQL__ADMIN_PASSWORD
          userPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD

redis:
  enabled: true
  global:
    storageClass: authentik-nfs
