server:
  volumeMounts:
    - name: authentik-assets
      mountPath: /static/dist/assets/images/custom
      subPath: images
      readOnly: true
  volumes:
    - name: authentik-assets
      nfs:
        server: truenas.home.albertv.dev
        path: /mnt/fast-1/k8s-nfs/authentik-assets
        readOnly: true
  envFrom:
    - secretRef:
        name: authentik-env

worker:
  envFrom:
    - secretRef:
        name: authentik-env

postgresql:
  enabled: true
  global:
    storageClass: authentik-nfs
    postgresql:
      auth:
        existingSecret: authentik-env
        secretKeys:
          adminPasswordKey: AUTHENTIK_POSTGRESQL__ADMIN_PASSWORD
          userPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD

redis:
  enabled: true
  global:
    storageClass: authentik-nfs
