server:
  envFrom:
    - secretRef:
        name: authentik-env

worker:
  envFrom:
    - secretRef:
        name: authentik-env

postgresql:
  enabled: true
  global:
    storageClass: authentik-nfs
    postgresql:
      auth:
        existingSecret: authentik-env
        secretKeys:
          adminPasswordKey: AUTHENTIK_POSTGRESQL__ADMIN_PASSWORD
          userPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD

redis:
  enabled: true
  global:
    storageClass: authentik-nfs
