{{ $name := include "base.component-fullname" (dict "context" $ "component" "cloudflare") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $name }}
spec:
  acme:
    email: albert.vaillon21@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ $name }}-issuer-private-key
    solvers:
      - dns01:
          cloudflare:
            email: albert.vaillon21@gmail.com
            apiTokenSecretRef:
              name: {{ $name }}-api-token
              key: api-token
