main:
  config:
    webhook:
      url: https://n8n.home.albertv.dev
    n8n:
      host: n8n.home.albertv.dev
      editor:
        base:
          url: https://n8n.home.albertv.dev
      proxy:
        hops: 1
