apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mimir
resources:
  - resources/ns.yaml
  - resources/mimir-lens-proxy-cm.yaml
  - resources/mimir-lens-proxy-deploy.yaml
  - resources/mimir-lens-proxy-svc.yaml
