apiVersion: v2
name: prowlarr
type: application
version: 1.0.0
# renovate: image=linuxserver/prowlarr
appVersion: 2.3.5
dependencies:
  - name: base
    version: 1.0.0
    repository: file://../../../base
