apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: media-server
spec:
  description: Project for media server applications
  sourceRepos:
    - "*"
  destinations:
    - namespace: jellyfin
    - namespace: sonarr
    - namespace: radarr
    - namespace: prowlarr
    - namespace: qbittorrent
    - namespace: bazarr
    - namespace: scraparr
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
