main:
  config:
    db:
      type: postgresdb
  extraEnv:
    DB_POSTGRESDB_HOST:
      valueFrom:
        secretKeyRef:
          name: n8n
          key: DB_POSTGRESDB_HOST
    DB_POSTGRESDB_USER:
      valueFrom:
        secretKeyRef:
          name: n8n
          key: DB_POSTGRESDB_USER
    DB_POSTGRESDB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: n8n
          key: DB_POSTGRESDB_PASSWORD
  persistence:
    enabled: true
    type: dynamic
    storageClass: nfs-ssd-1
    annotations:
      folder: n8n
