destinations:
  mimir:
    type: prometheus
    url: http://mimir-gateway.mimir.svc.cluster.local/api/v1/push
  loki:
    type: loki
    url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push

# Collectors
collectors:
  alloy-metrics:
    presets:
      - clustered
      - statefulset
  alloy-logs:
    presets:
      - filesystem-log-reader
      - daemonset
  alloy-singleton:
    presets:
      - singleton

# Features
clusterMetrics:
  enabled: true
  cadvisor:
    metricsTuning:
      useDefaultAllowList: false
  kube-state-metrics:
    metricsTuning:
      useDefaultAllowList: false
  collector: alloy-metrics

hostMetrics:
  enabled: true
  linuxHosts:
    enabled: true
    metricsTuning:
      useDefaultAllowList: false
  collector: alloy-metrics

telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true

clusterEvents:
  enabled: true
  collector: alloy-singleton

nodeLogs:
  enabled: true
  collector: alloy-logs

podLogsViaLoki:
  enabled: true
  collector: alloy-logs

prometheusOperatorObjects:
  enabled: true
  collector: alloy-metrics
