apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
spec:
  destination:
    namespace: argocd
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/syncPolicy/automated
        - /metadata/annotations/argocd.argoproj.io~1refresh
        - /operation
  revisionHistoryLimit: 10
