- op: add
  path: "/spec/template/spec/containers/0/startupProbe"
  value:
    httpGet:
      path: /api/dex/healthz
      port: 5556
      scheme: HTTPS
    initialDelaySeconds: 10
    timeoutSeconds: 5
- op: add
  path: "/spec/template/spec/containers/0/livenessProbe"
  value:
    httpGet:
      path: /api/dex/.well-known/openid-configuration
      port: 5556
      scheme: HTTPS
    initialDelaySeconds: 10
    timeoutSeconds: 5
