name: Test Build

on:
  pull_request:

jobs:
  kustomize-overlay-changes:
    name: Kustomize Overlay Changes
    runs-on: ubuntu-latest
    outputs:
      changed-overlays: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: build-filters
        name: Build Kustomize overlay filters
        run: |
          echo "filters<<EOF" >> $GITHUB_OUTPUT
          find . -path "*/overlays/*/kustomization.yaml" | while read file; do
            path=$(dirname "$file" | sed 's|^\./||')
            folder=$(echo "$path" | cut -d'/' -f1)
            echo "$path: $folder/**" >> $GITHUB_OUTPUT
          done
          echo "EOF" >> $GITHUB_OUTPUT

      - id: filter
        name: Filter Kustomize overlays with changes
        uses: dorny/paths-filter@v3
        with:
          filters: ${{ steps.build-filters.outputs.filters }}

  build-kustomize-overlay:
    name: Build Kustomize Overlay
    needs: kustomize-overlay-changes
    if: needs.kustomize-overlay-changes.outputs.changed-overlays != '[]'
    strategy:
      fail-fast: false
      matrix:
        overlay: ${{ fromJSON(needs.kustomize-overlay-changes.outputs.changed-overlays) }}
    runs-on: ubuntu-latest
    steps:
      - name: Build Kustomize overlay
        uses: eviive/actions/build/kustomize@main
        with:
          working-directory: ${{ matrix.overlay }}
