base:
  deployments:
    - containers:
        - name: sonarr
          image:
            repository: linuxserver/sonarr
            tag: 4.0.17@sha256:0b5c4803f92456fb9b65bae8375716ea120b4ea17b3cced7da32b63f0085782b
          env:
          - name: PUID
            value: "1057"
          - name: PGID
            value: "1056"
          ports:
            - name: http
              containerPort: 8989
          volumeMounts:
            - name: config
              mountPath: /config
            - name: shows
              mountPath: /tv
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: shows
          persistentVolumeClaim:
            claimName: sonarr-shows
        - name: downloads
          persistentVolumeClaim:
            claimName: sonarr-downloads

  pvcs:
    - name: config
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      storageClassName: nfs-ssd-1
      folder: media-server/sonarr/config
    - name: shows
      accessModes:
        - ReadWriteOnce
      size: 200Gi
      storageClassName: nfs-hdd-1
      folder: media-server/shows
    - name: downloads
      accessModes:
        - ReadWriteOnce
      size: 400Gi
      storageClassName: nfs-hdd-1
      folder: media-server/downloads

  services:
    - ports:
        - name: http
          port: 80
          targetPort: http

  ingressRoutes:
    - routes:
        - match: Host(`sonarr.home.albertv.dev`)
          services:
            - name: sonarr
              port: http
          enableAuthentikMiddleware: true
      authentikProxyProviderRouteMatch: Host(`sonarr.home.albertv.dev`)
      dnsNames:
        - sonarr.home.albertv.dev
