apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: media-server
spec:
  description: Project for media server applications
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
