apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: media-server
spec:
  description: Project for media server applications
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: storage.k8s.io
      kind: StorageClass
