apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
spec:
  description: Project for infrastructure applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
