apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
spec:
  description: Project for infrastructure applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: ServiceAccount
    - group: storage.k8s.io
      kind: StorageClass
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
